export enum AgeRating {
  GENERAL_AUDIENCE = "GENERAL_AUDIENCE",
  TEN_YEARS = "TEN_YEARS",
  TWELVE_YEARS = "TWELVE_YEARS",
  FOURTEEN_YEARS = "FOURTEEN_YEARS",
  SIXTEEN_YEARS = "SIXTEEN_YEARS",
  EIGHTEEN_YEARS = "EIGHTEEN_YEARS",
}

export enum MovieStatus {
  COMING_SOON = "COMING_SOON",
  NOW_PLAYING = "NOW_PLAYING",
  PAST_RELEASE = "PAST_RELEASE",
}

export enum Format {
  TWO_D = "TWO_D",
  THREE_D = "THREE_D",
}

export enum Subtitle {
  SUBTITLED = "SUBTITLED",
  DUBBED = "DUBBED",
  ORIGINAL = "ORIGINAL",
}
